// src/theme/themes.js
export const LightTheme = {
    statusbar: 'Black',
    background: '#8258D1',
    backgroundSecondary: '#F0F0F0',
    backgroundTertiary: '#F0F0F0',
    backgroundButtomHome:'#FFFFFF',
    tabBarBackground: '#8258D1',
    tabBarIconColor: 'white',
    colorIcon: 'white',
    colorIconBackground: '#4F3680',
    colorBackgroundCard: '#FFFFFF',
    textColor: '#4F3680',
    textColorSecondary: '#FFFFFF',
    textColorTertiary: '#FFFFFF',
    placeholderColor: '#F0F0F0',
    placeholderText: "4F3680",
    borderBottomColor: '#4F3680',
    buttonColor: '#4F3680',
};

export const DarkTheme = {
    statusbar: 'C5BDD8',
    background: '#250F4E',
    backgroundSecondary: '#250F4E',
    backgroundTertiary: '#130829',
    backgroundButtomHome:'#4F3680',
    tabBarBackground: '#250F4E',
    tabBarIconColor: '#C5BDD8',
    colorIcon: '#4F3680',
    colorIconBackground: '#C5BDD8',
    colorBackgroundCard: '#4F3680',
    textColor: '#C5BDD8',
    textColorSecondary: '#250F4E',
    textColorTertiary: '#4F3680',
    placeholderColor: '#C5BDD8',
    placeholderText: "4F3680",
    borderBottomColor: '#C5BDD8',
    buttonColor: '#C5BDD8',
};
