// src/theme/themes.js
export const LightTheme = {
    statusbar: 'Black',
    background: '#8258D1',
    backgroundSecondary: '#F0F0F0',
    backgroundTertiary: '#F0F0F0',
    backgroundButtomHome:'#FFFFFF',
    backgroundImput: '#FFFFFF',
    backgroundPerfil:'#FFFFFF',
    tabBarBackground: '#8258D1',
    tabBarIconColor: 'white',
    colorIcon: 'white',
    colorIconBackground: '#4F3680',
    colorBackgroundCard: '#FFFFFF',
    textColor: '#4F3680',
    textColorSecondary: '#FFFFFF',
    textColorTertiary: '#FFFFFF',
    textColorFourth: 'black',
    textColorLogin: '#6E7882',
    placeholderColor: '#F0F0F0',
    placeholderText: "#4F3680",
    borderBottomColor: '#4F3680',
    buttonColor: '#4F3680',
    modalBackground: '#FFFFFF',
    modalButton: '#4F3680',
    modalButtonText: '#4F3680',
    modalButtonClose: '#ccc',
    modalButtonCloseText: '#4F3680',
};

export const DarkTheme = {
    statusbar: 'white',
    background: '#250F4E',
    backgroundSecondary: '#250F4E',
    backgroundTertiary: '#130829',
    backgroundButtomHome:'#4F3680',
    backgroundImput: '#C5BDD8',
    backgroundPerfil:'#130829',
    tabBarBackground: '#250F4E',
    tabBarIconColor: '#C5BDD8',
    colorIcon: '#4F3680',
    colorIconBackground: '#C5BDD8',
    colorBackgroundCard: '#4F3680',
    textColor: '#C5BDD8',
    textColorSecondary: '#250F4E',
    textColorTertiary: '#4F3680',
    textColorFourth: '#C5BDD8',
    textColorLogin: '#4F3680',
    placeholderColor: '#C5BDD8',
    placeholderText: "#4F3680",
    borderBottomColor: '#C5BDD8',
    buttonColor: '#C5BDD8',
    modalBackground: '#4F3680',
    modalButton: '#1C0E37',
    modalButtonText: '#4F3680',
    modalButtonClose: '#C5BDD8',
    modalButtonCloseText: '#4F3680',
};
